#!/usr/bin/env bash
# regenerate_skills.sh
# Refreshes .github/skills/<package>-usage/SKILL.md files so they match the
# exact versions installed in pubspec.lock.
#
# Usage:
#   bash scripts/regenerate_skills.sh              # check which skills are stale
#   bash scripts/regenerate_skills.sh --write      # write/update stale skill files

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

WRITE=false
for arg in "$@"; do
  case "$arg" in
    --write) WRITE=true ;;
    *) echo "Unknown flag: $arg" >&2; exit 1 ;;
  esac
done

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required. Install with: brew install jq" >&2
  exit 1
fi

echo ""
echo "=== miToosa Skill Freshness Check ==="
echo "Date: $(date -u '+%Y-%m-%d %H:%M UTC')"
echo ""

# Read direct dependencies from pubspec.yaml
DIRECT_DEPS=$(grep -E '^\s{2}[a-z_]+:' pubspec.yaml \
  | grep -v 'flutter:' \
  | sed 's/://g' \
  | sed 's/^[[:space:]]*//' \
  | sort -u)

STALE_COUNT=0
MISSING_COUNT=0

while IFS= read -r pkg; do
  [[ -z "$pkg" ]] && continue

  # Get exact installed version from pubspec.lock
  INSTALLED=$(grep -A 3 "^  ${pkg}:" pubspec.lock 2>/dev/null \
    | grep 'version:' \
    | head -1 \
    | sed 's/.*version: "\(.*\)"/\1/' \
    | tr -d ' ')

  if [[ -z "$INSTALLED" ]]; then
    # Package might be an SDK dep (flutter, dart) — skip
    continue
  fi

  SKILL_FILE="${REPO_ROOT}/.github/skills/${pkg}-usage/SKILL.md"

  if [[ ! -f "$SKILL_FILE" ]]; then
    echo "  MISSING skill: ${pkg} (installed: ${INSTALLED})"
    MISSING_COUNT=$((MISSING_COUNT + 1))

    if [ "$WRITE" = true ]; then
      mkdir -p "$(dirname "$SKILL_FILE")"
      # Fetch latest readme text from pub.dev (best-effort)
      PUB_README=$(curl -sL --max-time 10 \
        "https://pub.dev/api/packages/${pkg}/versions/${INSTALLED}" 2>/dev/null \
        | jq -r '.pubspec.description // "No description available."' 2>/dev/null \
        || echo "No description available.")

      cat > "$SKILL_FILE" <<SKILL_EOF
---
name: ${pkg}-usage
description: How to use ${pkg} v${INSTALLED} in miToosa. Generated from pub.dev docs — not from memory.
version: ${INSTALLED}
source: https://pub.dev/packages/${pkg}/versions/${INSTALLED}
generated: $(date -u '+%Y-%m-%d')
---

# ${pkg} v${INSTALLED}

> Auto-generated by \`scripts/regenerate_skills.sh\` on $(date -u '+%Y-%m-%d').
> Re-run with \`--write\` after upgrading to keep this file current.

## pubspec.yaml Entry

\`\`\`yaml
${pkg}: ^${INSTALLED}
\`\`\`

## Description

${PUB_README}

## Documentation

- pub.dev: https://pub.dev/packages/${pkg}/versions/${INSTALLED}
- Changelog: https://pub.dev/packages/${pkg}/changelog

## Key APIs

> Fetch the pub.dev README for v${INSTALLED} and fill this section in.
> Run: curl -sL "https://pub.dev/packages/${pkg}/versions/${INSTALLED}"

## Patterns Used in miToosa

> Search \`lib/\` for usages of this package and document them here.

## Migration Notes

> If upgrading from a previous version, extract breaking changes from the
> CHANGELOG at https://pub.dev/packages/${pkg}/changelog
SKILL_EOF
      echo "    → Created: ${SKILL_FILE}"
    fi
  else
    # Check version in existing skill
    SKILL_VERSION=$(grep '^version:' "$SKILL_FILE" | sed 's/version: //' | tr -d ' ')

    if [[ "$SKILL_VERSION" != "$INSTALLED" ]]; then
      echo "  STALE skill: ${pkg} (skill: ${SKILL_VERSION}, installed: ${INSTALLED})"
      STALE_COUNT=$((STALE_COUNT + 1))

      if [ "$WRITE" = true ]; then
        # Update the version line and generated date in the skill header
        sed -i.bak \
          -e "s/^version: .*/version: ${INSTALLED}/" \
          -e "s|^source: .*|source: https://pub.dev/packages/${pkg}/versions/${INSTALLED}|" \
          -e "s/^generated: .*/generated: $(date -u '+%Y-%m-%d')/" \
          "$SKILL_FILE"
        rm -f "${SKILL_FILE}.bak"
        echo "    → Updated version to ${INSTALLED} in: ${SKILL_FILE}"
      fi
    else
      echo "  OK  ${pkg} @ ${INSTALLED}"
    fi
  fi
done <<< "$DIRECT_DEPS"

echo ""
echo "--- Summary ---"
echo "Missing skills: ${MISSING_COUNT}"
echo "Stale skills:   ${STALE_COUNT}"

if [ "$WRITE" = false ] && [ $((MISSING_COUNT + STALE_COUNT)) -gt 0 ]; then
  echo ""
  echo "Run with --write to create/update stale skill files."
fi

echo ""
echo "=== Done ==="
